"""empty message

Revision ID: 997b18f5df04
Revises: 6c04946aed7f
Create Date: 2024-03-03 19:44:17.990955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997b18f5df04'
down_revision: Union[str, None] = '6c04946aed7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('maturity', sa.Float(asdecimal=True), nullable=False),
    sa.Column('value', sa.Float(asdecimal=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['interest_rate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swaption_vol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('tenor', sa.Float(asdecimal=True), nullable=False),
    sa.Column('maturity', sa.Float(asdecimal=True), nullable=False),
    sa.Column('value', sa.Float(asdecimal=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['interest_rate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swaption_vol')
    op.drop_table('interest_rate')
    # ### end Alembic commands ###
